In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import sklearn as skt

In [3]:
#Array tem um unico tipo de dados
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#editar valores do array
array[0] = 9
print(array[0])
print(array)

9
[9 2 3 4 5 6]


In [8]:
#matriz
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)

In [14]:
print("Max: ", notas.max())
print("Min: ", notas.min())
print("Desvio Padrao: ", notas.std())
print("Media: ", notas.mean())
print("Posicao Menor: ", notas.argmin())

Max:  9.8
Min:  5.6
Desvio Padrao:  1.5628179676469045
Media:  7.76
Posicao Menor:  1


In [19]:
#Desafio numpy
lista = []
alunos = int(input("Quantos alunos tem na Sala: "))
for i in range(0,alunos):
    notas = float(input(f"Qual nota do aluno {i +1}: "))
    lista.append(notas)

array_notas = np.array(lista)
print(array_notas)

Quantos alunos tem na Sala:  5
Qual nota do aluno 1:  5.6
Qual nota do aluno 2:  7.8
Qual nota do aluno 3:  9.0
Qual nota do aluno 4:  4.2
Qual nota do aluno 5:  5.9


[5.6 7.8 9.  4.2 5.9]


In [21]:
#Análise do Desafio
print("Nota Maxima: ", array_notas.max())
print("Nota Minima: ", array_notas.min())
print("Desvio Padrao: ", array_notas.std())
print("Media: ", array_notas.mean())
print("Posicao Menor: ", array_notas.argmin())

Nota Maxima:  9.0
Nota Minima:  4.2
Desvio Padrao:  1.697056274847714
Media:  6.5
Posicao Menor:  3


In [24]:
#Mascara Booleana
is_covid_positive = np.array(['Yes', 'No', 'No', 'Yes','Yes','No'])

In [25]:
mask = (is_covid_positive == 'Yes')

In [26]:
print(mask)

[ True False False  True  True False]


In [29]:
#Alterando o array para os casos mask
is_covid_positive[mask] = 'C19'
print(is_covid_positive)

['C19' 'No' 'No' 'C19' 'C19' 'No']


In [30]:
notas = np.array([4.9, 6.5, 3.2, 6.7])
mask_notas = notas >= 5

In [31]:
print(mask_notas)

[False  True False  True]


In [40]:
#Desafio numpy mascara Booleana
lista2 = []
alunos2 = int(input("Quantos alunos tem na Sala: "))
for i in range(0,alunos2):
    notas2 = float(input(f"Qual nota do aluno {i +1}: "))
    lista2.append(notas2)

array_notas2 = np.array(lista2)
print(array_notas2)

Quantos alunos tem na Sala:  5
Qual nota do aluno 1:  6.3
Qual nota do aluno 2:  6.2
Qual nota do aluno 3:  7.8
Qual nota do aluno 4:  3.5
Qual nota do aluno 5:  5.9


[6.3 6.2 7.8 3.5 5.9]


In [45]:
print("Nota necessária para Passar, maior ou igual a 6.2")
mask_notas2 = array_notas2 >= 6.2
print(mask_notas2)
mask_recuperacao = (array_notas2 < 6.2)
alunos_recuperacao = array_notas2[mask_recuperacao]
print('Alunos de recuperacao:', alunos_recuperacao)

Nota necessária para Passar, maior ou igual a 6.2
[ True  True  True False False]
Alunos de recuperacao: [3.5 5.9]
